import React, { useState } from 'react';
import { db } from './firebase'; 
import { collection, writeBatch, doc } from "firebase/firestore";

const AdminPanel = () => {
  const [bulkData, setBulkData] = useState('');
    const [loading, setLoading] = useState(false);

      const handleBulkUpload = async () => {
          if (!bulkData.trim()) return alert("Bhai, pehle data toh daal!");
              setLoading(true);
                  try {
                        const rows = bulkData.trim().split('\n');
                              const batch = writeBatch(db);

                                    rows.forEach((row) => {
                                            const [subject, unit, chapter, qText, optA, optB, optC, optD, correct, tags] = row.split(',');
                                                    if (subject && qText) {
                                                              const qRef = doc(collection(db, "questions"));
                                                                        batch.set(qRef, {
                                                                                    subject: subject.trim(),
                                                                                                unit: unit.trim(),
                                                                                                            chapter: chapter.trim(),
                                                                                                                        questionText: qText.trim(),
                                                                                                                                    options: { A: optA.trim(), B: optB.trim(), C: optC.trim(), D: optD.trim() },
                                                                                                                                                correctAnswer: correct.trim(),
                                                                                                                                                            tags: tags ? tags.split(';') : [],
                                                                                                                                                                        createdAt: new Date()
                                                                                                                                                                                  });
                                                                                                                                                                                          }
                                                                                                                                                                                                });

                                                                                                                                                                                                      await batch.commit();
                                                                                                                                                                                                            alert("Bhai, saara data Firestore mein chala gaya! 🚀");
                                                                                                                                                                                                                  setBulkData('');
                                                                                                                                                                                                                      } catch (e) {
                                                                                                                                                                                                                            console.error(e);
                                                                                                                                                                                                                                  alert("Error: " + e.message);
                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                          setLoading(false);
                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                  <div className="p-6 bg-gray-50 min-h-screen flex flex-col items-center">
                                                                                                                                                                                                                                                        <h2 className="text-2xl font-black text-blue-900 mb-6 tracking-tight">medACE Admin Panel</h2>
                                                                                                                                                                                                                                                              <div className="w-full max-w-2xl bg-white p-6 rounded-[2rem] shadow-sm border border-gray-100">
                                                                                                                                                                                                                                                                      <h3 className="font-bold text-gray-700 mb-2">Bulk Upload (CSV Format)</h3>
                                                                                                                                                                                                                                                                              <p className="text-[10px] text-gray-400 mb-4 uppercase font-bold tracking-widest">Format: Subject,Unit,Chapter,Question,A,B,C,D,Correct,Tags</p>
                                                                                                                                                                                                                                                                                      <textarea 
                                                                                                                                                                                                                                                                                                value={bulkData}
                                                                                                                                                                                                                                                                                                          onChange={(e) => setBulkData(e.target.value)}
                                                                                                                                                                                                                                                                                                                    className="w-full h-48 p-4 bg-gray-50 rounded-2xl border-none focus:ring-2 focus:ring-blue-500 font-mono text-sm mb-4"
                                                                                                                                                                                                                                                                                                                              placeholder="Anatomy,Upper Limb,Brachial Plexus,Erb's Palsy roots?,C5-C6,C8-T1,C7,C5-T1,A,PYQ"
                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                              <button 
                                                                                                                                                                                                                                                                                                                                                        onClick={handleBulkUpload}
                                                                                                                                                                                                                                                                                                                                                                  disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                            className="w-full bg-green-500 hover:bg-green-600 text-white font-black py-4 rounded-2xl transition-all shadow-lg shadow-green-100 disabled:opacity-50"
                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                              {loading ? "Uploading..." : "Upload All 🚀"}
                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                  export default AdminPanel;
                                                                                                                                                                                                                                                                                                                                                                                                                  