import React, { useState } from 'react';
import StudentDashboard from './StudentDashboard';
import AdminPanel from './AdminPanel';

const MedAcePro = ({ user }) => {
  const [view, setView] = useState('hub'); // 'hub', 'practice', 'admin', 'leaderboard', 'bookmarks'
    const [isSidebarOpen, setIsSidebarOpen] = useState(false);

      const fixedSubjects = [
          { name: 'Anatomy', icon: '🦴', color: 'bg-orange-100 text-orange-600' },
              { name: 'Physiology', icon: '🫀', color: 'bg-red-100 text-red-600' },
                  { name: 'Biochemistry', icon: '🧪', color: 'bg-blue-100 text-blue-600' },
                      { name: 'Pathology', icon: '🔬', color: 'bg-purple-100 text-purple-600' },
                          { name: 'Pharmacology', icon: '💊', color: 'bg-emerald-100 text-emerald-600' },
                              { name: 'Microbiology', icon: '🧫', color: 'bg-yellow-100 text-yellow-700' },
                                  { name: 'Forensic Medicine', icon: '⚖️', color: 'bg-slate-200 text-slate-700' },
                                      { name: 'PSM', icon: '🏥', color: 'bg-cyan-100 text-cyan-600' },
                                          { name: 'ENT', icon: '👂', color: 'bg-rose-100 text-rose-600' },
                                              { name: 'Ophthalmology', icon: '👁️', color: 'bg-indigo-100 text-indigo-600' },
                                                  { name: 'Medicine', icon: '🩺', color: 'bg-blue-200 text-blue-800' },
                                                      { name: 'Surgery', icon: '🔪', color: 'bg-red-200 text-red-800' },
                                                          { name: 'OBG', icon: '👶', color: 'bg-pink-100 text-pink-600' },
                                                              { name: 'Pediatrics', icon: '🍼', color: 'bg-amber-100 text-amber-600' },
                                                                  { name: 'Orthopedics', icon: '🦾', color: 'bg-stone-200 text-stone-700' },
                                                                      { name: 'Dermatology', icon: '🧴', color: 'bg-orange-50 text-orange-700' },
                                                                          { name: 'Psychiatry', icon: '🧠', color: 'bg-violet-100 text-violet-600' },
                                                                              { name: 'Radiology', icon: '☢️', color: 'bg-gray-800 text-white' },
                                                                                  { name: 'Anaesthesia', icon: '😴', color: 'bg-teal-100 text-teal-600' }
                                                                                    ];

                                                                                      const authorizedEmails = ["medace.admin@gmail.com"]; 
                                                                                        const isAdmin = user && authorizedEmails.includes(user.email.toLowerCase());

                                                                                          return (
                                                                                              <div className="relative min-h-screen bg-slate-50">
                                                                                                    {/* GLOBAL SLIDER MENU CONTROLLER */}
                                                                                                          {isSidebarOpen && (
                                                                                                                  <div className="fixed inset-0 z-[100] flex">
                                                                                                                            <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-xs" onClick={() => setIsSidebarOpen(false)} />
                                                                                                                                      <div className="relative w-72 max-w-sm bg-slate-900 h-full text-white shadow-2xl flex flex-col p-6">
                                                                                                                                                  <div className="flex items-center justify-between mb-8 border-b border-white/10 pb-4">
                                                                                                                                                                <div>
                                                                                                                                                                                <h2 className="text-2xl font-black italic text-blue-400">medACE</h2>
                                                                                                                                                                                                <p className="text-[10px] text-gray-400 font-bold uppercase">MBBS Command Deck</p>
                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                            <button onClick={() => setIsSidebarOpen(false)} className="w-8 h-8 rounded-full bg-white/10 flex items-center justify-center font-bold">✕</button>
                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                    <nav className="flex-1 space-y-2.5">
                                                                                                                                                                                                                                                                  <button onClick={() => { setView('hub'); setIsSidebarOpen(false); }} className={`w-full text-left p-3.5 rounded-2xl font-black text-xs uppercase ${view === 'hub' ? 'bg-blue-600 text-white' : 'text-gray-300'}`}>📊 Dashboard / Q-Bank</button>
                                                                                                                                                                                                                                                                                <button onClick={() => { setView('leaderboard'); setIsSidebarOpen(false); }} className={`w-full text-left p-3.5 rounded-2xl font-black text-xs uppercase ${view === 'leaderboard' ? 'bg-blue-600 text-white' : 'text-gray-300'}`}>🏆 Leaderboard</button>
                                                                                                                                                                                                                                                                                              <button onClick={() => { setView('bookmarks'); setIsSidebarOpen(false); }} className={`w-full text-left p-3.5 rounded-2xl font-black text-xs uppercase ${view === 'bookmarks' ? 'bg-blue-600 text-white' : 'text-gray-300'}`}>🔖 Saved Bookmarks</button>
                                                                                                                                                                                                                                                                                                            {isAdmin && <button onClick={() => { setView('admin'); setIsSidebarOpen(false); }} className={`w-full text-left p-3.5 rounded-2xl font-black text-xs uppercase ${view === 'admin' ? 'bg-amber-600 text-white' : 'text-amber-400'}`}>⚙️ Admin Control</button>}
                                                                                                                                                                                                                                                                                                                        </nav>
                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                      {/* CONDITIONAL COMPONENT ROUTER ENGINE */}
                                                                                                                                                                                                                                                                                                                                                            {view === 'admin' && isAdmin ? (
                                                                                                                                                                                                                                                                                                                                                                    <AdminPanel setIsSidebarOpen={setIsSidebarOpen} fixedSubjects={fixedSubjects} />
                                                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                                                  <StudentDashboard 
                                                                                                                                                                                                                                                                                                                                                                                            user={user} 
                                                                                                                                                                                                                                                                                                                                                                                                      view={view} 
                                                                                                                                                                                                                                                                                                                                                                                                                setView={setView} 
                                                                                                                                                                                                                                                                                                                                                                                                                          isSidebarOpen={isSidebarOpen} 
                                                                                                                                                                                                                                                                                                                                                                                                                                    setIsSidebarOpen={setIsSidebarOpen} 
                                                                                                                                                                                                                                                                                                                                                                                                                                              fixedSubjects={fixedSubjects}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        isAdmin={isAdmin}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default MedAcePro;
